//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogItem
    {
        public int CMCID { get; set; }
        public int ComponentId { get; set; }
        public int MaterialCategoryId { get; set; }
        public int ComponentTypeId { get; set; }
        public int UoM { get; set; }
        public int ComponentUiiId { get; set; }
        public decimal AdjFactor { get; set; }
        public decimal CII { get; set; }
        public Nullable<int> TaskListId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public System.Guid BUILDERInstanceId { get; set; }
        public string CreatedByUserId { get; set; }
        public Nullable<int> UseAltDesc { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BUILDERInstance BUILDERInstance { get; set; }
    }
}
