//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int ComponentId { get; set; }
        public int SystemId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsUii { get; set; }
        public string UiiCode { get; set; }
        public Nullable<bool> IsEquip { get; set; }
        public string CreatedByUserId { get; set; }
        public System.Guid BUILDERInstanceId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BUILDERInstance BUILDERInstance { get; set; }
    }
}
